/**
 * Bulk logo domain list — ~1 200 well-known brand domains.
 * Each entry is [domain, displayName].
 * Used by !logo bulkfetch to probe logo.dev for valid images.
 */
export const BULK_DOMAINS: [string, string][] = [
  // ── Technology & Software ──────────────────────────────────────────────────
  ["vercel.com", "Vercel"],
  ["cloudflare.com", "Cloudflare"],
  ["openai.com", "OpenAI"],
  ["anthropic.com", "Anthropic"],
  ["replit.com", "Replit"],
  ["gitlab.com", "GitLab"],
  ["atlassian.com", "Atlassian"],
  ["trello.com", "Trello"],
  ["asana.com", "Asana"],
  ["monday.com", "Monday.com"],
  ["zendesk.com", "Zendesk"],
  ["hubspot.com", "HubSpot"],
  ["mailchimp.com", "Mailchimp"],
  ["twilio.com", "Twilio"],
  ["square.com", "Square"],
  ["plaid.com", "Plaid"],
  ["robinhood.com", "Robinhood"],
  ["kraken.com", "Kraken"],
  ["digitalocean.com", "DigitalOcean"],
  ["netlify.com", "Netlify"],
  ["heroku.com", "Heroku"],
  ["linode.com", "Linode"],
  ["supabase.com", "Supabase"],
  ["firebase.google.com", "Firebase"],
  ["mongodb.com", "MongoDB"],
  ["redis.io", "Redis"],
  ["elastic.co", "Elastic"],
  ["datadog.com", "Datadog"],
  ["splunk.com", "Splunk"],
  ["pagerduty.com", "PagerDuty"],
  ["newrelic.com", "New Relic"],
  ["sentry.io", "Sentry"],
  ["grafana.com", "Grafana"],
  ["hashicorp.com", "HashiCorp"],
  ["terraform.io", "Terraform"],
  ["ansible.com", "Ansible"],
  ["redhat.com", "Red Hat"],
  ["ubuntu.com", "Ubuntu"],
  ["debian.org", "Debian"],
  ["archlinux.org", "Arch Linux"],
  ["git-scm.com", "Git"],
  ["docker.com", "Docker"],
  ["kubernetes.io", "Kubernetes"],
  ["helm.sh", "Helm"],
  ["nginx.com", "NGINX"],
  ["apache.org", "Apache"],
  ["jetbrains.com", "JetBrains"],
  ["unity.com", "Unity"],
  ["unrealengine.com", "Unreal Engine"],
  ["blender.org", "Blender"],
  ["gimp.org", "GIMP"],
  ["inkscape.org", "Inkscape"],
  ["godotengine.org", "Godot"],
  ["webflow.com", "Webflow"],
  ["squarespace.com", "Squarespace"],
  ["wix.com", "Wix"],
  ["ghost.org", "Ghost"],
  ["wordpress.com", "WordPress"],
  ["framer.com", "Framer"],
  ["tailwindcss.com", "Tailwind CSS"],
  ["svelte.dev", "Svelte"],
  ["vuejs.org", "Vue.js"],
  ["react.dev", "React"],
  ["nextjs.org", "Next.js"],
  ["nuxt.com", "Nuxt"],
  ["angular.io", "Angular"],
  ["nodejs.org", "Node.js"],
  ["deno.com", "Deno"],
  ["bun.sh", "Bun"],
  ["python.org", "Python"],
  ["rust-lang.org", "Rust"],
  ["golang.org", "Go"],
  ["kotlin.org", "Kotlin"],
  ["swift.org", "Swift"],
  ["typescriptlang.org", "TypeScript"],
  ["postgresql.org", "PostgreSQL"],
  ["mysql.com", "MySQL"],
  ["sqlite.org", "SQLite"],
  ["mariadb.org", "MariaDB"],
  ["stripe.com", "Stripe"],
  ["twitch.tv", "Twitch"],
  // ── Social Media & Communication ───────────────────────────────────────────
  ["tumblr.com", "Tumblr"],
  ["medium.com", "Medium"],
  ["substack.com", "Substack"],
  ["bereal.com", "BeReal"],
  ["mastodon.social", "Mastodon"],
  ["signal.org", "Signal"],
  ["skype.com", "Skype"],
  ["teams.microsoft.com", "Microsoft Teams"],
  ["webex.com", "Webex"],
  ["viber.com", "Viber"],
  ["line.me", "LINE"],
  ["wechat.com", "WeChat"],
  ["kakao.com", "Kakao"],
  ["vk.com", "VKontakte"],
  ["odnoklassniki.ru", "Odnoklassniki"],
  // ── E-commerce & Retail ────────────────────────────────────────────────────
  ["ebay.com", "eBay"],
  ["etsy.com", "Etsy"],
  ["aliexpress.com", "AliExpress"],
  ["alibaba.com", "Alibaba"],
  ["shein.com", "SHEIN"],
  ["asos.com", "ASOS"],
  ["gap.com", "Gap"],
  ["forever21.com", "Forever 21"],
  ["primark.com", "Primark"],
  ["lidl.com", "Lidl"],
  ["aldi.com", "Aldi"],
  ["walmart.com", "Walmart"],
  ["costco.com", "Costco"],
  ["kroger.com", "Kroger"],
  ["carrefour.com", "Carrefour"],
  ["tesco.com", "Tesco"],
  ["sainsburys.co.uk", "Sainsbury's"],
  ["morrisons.com", "Morrisons"],
  ["waitrose.com", "Waitrose"],
  ["marks-and-spencer.com", "Marks & Spencer"],
  ["rewe.de", "REWE"],
  ["edeka.de", "EDEKA"],
  ["kaufland.de", "Kaufland"],
  ["mercadona.es", "Mercadona"],
  ["mediamarkt.com", "MediaMarkt"],
  ["saturn.de", "Saturn"],
  ["bestbuy.com", "Best Buy"],
  ["newegg.com", "Newegg"],
  ["chewy.com", "Chewy"],
  ["wayfair.com", "Wayfair"],
  ["overstock.com", "Overstock"],
  ["wish.com", "Wish"],
  ["vinted.com", "Vinted"],
  ["depop.com", "Depop"],
  ["poshmark.com", "Poshmark"],
  ["thredup.com", "ThredUp"],
  ["farfetch.com", "Farfetch"],
  ["net-a-porter.com", "Net-a-Porter"],
  ["mytheresa.com", "Mytheresa"],
  ["ssense.com", "SSENSE"],
  ["kith.com", "Kith"],
  ["superdry.com", "Superdry"],
  ["jackjones.com", "Jack & Jones"],
  ["hm.com", "H&M"],
  ["mango.com", "Mango"],
  ["massimodutti.com", "Massimo Dutti"],
  ["pullandbear.com", "Pull&Bear"],
  ["bershka.com", "Bershka"],
  ["stradivarius.com", "Stradivarius"],
  ["weekday.com", "Weekday"],
  ["cos.com", "COS"],
  ["arket.com", "ARKET"],
  ["& other stories.com", "& Other Stories"],
  ["lululemon.com", "lululemon"],
  ["gymshark.com", "Gymshark"],
  ["hollister.com", "Hollister"],
  ["abercrombie.com", "Abercrombie & Fitch"],
  ["americaneagle.com", "American Eagle"],
  ["urbanoutfitters.com", "Urban Outfitters"],
  ["anthropologie.com", "Anthropologie"],
  ["freepeople.com", "Free People"],
  ["topshop.com", "Topshop"],
  ["next.co.uk", "Next"],
  ["johnlewis.com", "John Lewis"],
  ["debenhams.com", "Debenhams"],
  ["river-island.com", "River Island"],
  ["newlook.com", "New Look"],
  // ── Food & Beverages ───────────────────────────────────────────────────────
  ["yum.com", "Yum! Brands"],
  ["pepsico.com", "PepsiCo"],
  ["kelloggs.com", "Kellogg's"],
  ["generalmills.com", "General Mills"],
  ["mondelez.com", "Mondelez"],
  ["unilever.com", "Unilever"],
  ["kraftheinz.com", "Kraft Heinz"],
  ["mars.com", "Mars"],
  ["ferrero.com", "Ferrero"],
  ["lindt.com", "Lindt"],
  ["godiva.com", "Godiva"],
  ["haagen-dazs.com", "Häagen-Dazs"],
  ["baskinrobbins.com", "Baskin-Robbins"],
  ["dairyqueen.com", "Dairy Queen"],
  ["fiveguys.com", "Five Guys"],
  ["shakeshack.com", "Shake Shack"],
  ["panerabread.com", "Panera Bread"],
  ["chickfila.com", "Chick-fil-A"],
  ["wendys.com", "Wendy's"],
  ["jackinthe box.com", "Jack in the Box"],
  ["sonicdrivein.com", "Sonic"],
  ["popeyes.com", "Popeyes"],
  ["tacobell.com", "Taco Bell"],
  ["papajohns.com", "Papa John's"],
  ["littlecaesars.com", "Little Caesars"],
  ["pandaexpress.com", "Panda Express"],
  ["whataburger.com", "Whataburger"],
  ["innout.com", "In-N-Out Burger"],
  ["smashburger.com", "Smashburger"],
  ["wingstop.com", "Wingstop"],
  ["buffalowildwings.com", "Buffalo Wild Wings"],
  ["applebees.com", "Applebee's"],
  ["olivegarden.com", "Olive Garden"],
  ["redlobster.com", "Red Lobster"],
  ["texasroadhouse.com", "Texas Roadhouse"],
  ["outback.com", "Outback Steakhouse"],
  ["ihop.com", "IHOP"],
  ["dennys.com", "Denny's"],
  ["cracker barrel.com", "Cracker Barrel"],
  ["redrobin.com", "Red Robin"],
  ["tgifridays.com", "TGI Fridays"],
  ["hardees.com", "Hardee's"],
  ["carlsjr.com", "Carl's Jr"],
  ["krispykreme.com", "Krispy Kreme"],
  ["timshortons.com", "Tim Hortons"],
  ["peets.com", "Peet's Coffee"],
  ["dunkindonuts.com", "Dunkin'"],
  ["costacoffe.com", "Costa Coffee"],
  ["paulcafe.com", "Paul"],
  ["lavazza.com", "Lavazza"],
  ["illy.com", "illy"],
  ["jacobs.com", "Jacobs"],
  ["tchibo.com", "Tchibo"],
  ["red-bull.com", "Red Bull"],
  ["monsterenergy.com", "Monster Energy"],
  ["rockstarenergy.com", "Rockstar Energy"],
  ["celsiusdrink.com", "Celsius"],
  ["gatorade.com", "Gatorade"],
  ["powerade.com", "Powerade"],
  ["aquafina.com", "Aquafina"],
  ["evian.com", "Evian"],
  ["volvic.com", "Volvic"],
  ["perrier.com", "Perrier"],
  ["sanpellegrino.com", "San Pellegrino"],
  ["badoit.fr", "Badoit"],
  ["corona.com", "Corona"],
  ["budweiser.com", "Budweiser"],
  ["carlsberg.com", "Carlsberg"],
  ["guinness.com", "Guinness"],
  ["stella artois.com", "Stella Artois"],
  ["becks.com", "Beck's"],
  ["hoegaarden.com", "Hoegaarden"],
  ["leffe.com", "Leffe"],
  ["tuborg.com", "Tuborg"],
  ["desperados.com", "Desperados"],
  ["smirnoff.com", "Smirnoff"],
  ["absolut.com", "Absolut"],
  ["jackdaniels.com", "Jack Daniel's"],
  ["jimbeam.com", "Jim Beam"],
  ["johnniewalker.com", "Johnnie Walker"],
  ["chivas.com", "Chivas Regal"],
  ["glenfiddich.com", "Glenfiddich"],
  ["glenlivet.com", "The Glenlivet"],
  ["baileys.com", "Baileys"],
  ["grey-goose.com", "Grey Goose"],
  ["patron.com", "Patron"],
  ["hennessy.com", "Hennessy"],
  ["martell.com", "Martell"],
  ["moetchandon.com", "Moët & Chandon"],
  ["veuve-clicquot.com", "Veuve Clicquot"],
  ["mumm.com", "G.H. Mumm"],
  ["perrier-jouet.com", "Perrier-Jouët"],
  ["dom-perignon.com", "Dom Pérignon"],
  // ── Automotive ─────────────────────────────────────────────────────────────
  ["rivian.com", "Rivian"],
  ["lucidmotors.com", "Lucid Motors"],
  ["nio.com", "NIO"],
  ["byd.com", "BYD"],
  ["genesis.com", "Genesis"],
  ["infinitiusa.com", "Infiniti"],
  ["acura.com", "Acura"],
  ["lexus.com", "Lexus"],
  ["cadillac.com", "Cadillac"],
  ["buick.com", "Buick"],
  ["gmc.com", "GMC"],
  ["ram.com", "RAM"],
  ["dodge.com", "Dodge"],
  ["chrysler.com", "Chrysler"],
  ["lincoln.com", "Lincoln"],
  ["opel.com", "Opel"],
  ["vauxhall.co.uk", "Vauxhall"],
  ["dacia.com", "Dacia"],
  ["lancia.com", "Lancia"],
  ["ssangyong.com", "SsangYong"],
  ["haval.com", "Haval"],
  ["great-wall.com", "Great Wall"],
  ["tesla.com", "Tesla"],
  ["bmwmotorrad.com", "BMW Motorrad"],
  ["triumph.co.uk", "Triumph"],
  ["ducati.com", "Ducati"],
  ["kawasaki.com", "Kawasaki"],
  ["yamaha-motor.com", "Yamaha Motor"],
  ["honda.com", "Honda"],
  ["suzuki.com", "Suzuki"],
  ["ktm.com", "KTM"],
  ["vespa.com", "Vespa"],
  ["piaggio.com", "Piaggio"],
  ["polaris.com", "Polaris"],
  ["cannondale.com", "Cannondale"],
  ["specialized.com", "Specialized"],
  ["trekbikes.com", "Trek Bikes"],
  ["giantbicycles.com", "Giant"],
  // ── Airlines ───────────────────────────────────────────────────────────────
  ["delta.com", "Delta Air Lines"],
  ["united.com", "United Airlines"],
  ["aa.com", "American Airlines"],
  ["southwest.com", "Southwest Airlines"],
  ["jetblue.com", "JetBlue"],
  ["alaskaair.com", "Alaska Airlines"],
  ["flyfrontier.com", "Frontier Airlines"],
  ["spirit.com", "Spirit Airlines"],
  ["wizzair.com", "Wizz Air"],
  ["easyjet.com", "easyJet"],
  ["vueling.com", "Vueling"],
  ["iberia.com", "Iberia"],
  ["flytap.com", "TAP Portugal"],
  ["finnair.com", "Finnair"],
  ["klm.com", "KLM"],
  ["turkishairlines.com", "Turkish Airlines"],
  ["qatarairways.com", "Qatar Airways"],
  ["etihad.com", "Etihad Airways"],
  ["cathaypacific.com", "Cathay Pacific"],
  ["flyasiana.com", "Asiana Airlines"],
  ["koreanair.com", "Korean Air"],
  ["vietjetair.com", "VietJet Air"],
  ["airasia.com", "AirAsia"],
  ["lionair.com", "Lion Air"],
  ["batikair.com", "Batik Air"],
  ["aeromexico.com", "Aeromexico"],
  ["lan.com", "LATAM"],
  ["avianca.com", "Avianca"],
  ["copaair.com", "Copa Airlines"],
  ["flydubai.com", "flydubai"],
  ["indigoairlines.com", "IndiGo"],
  ["airindia.com", "Air India"],
  ["spicejet.com", "SpiceJet"],
  // ── Hotels & Travel ────────────────────────────────────────────────────────
  ["hyatt.com", "Hyatt"],
  ["ihg.com", "IHG"],
  ["accor.com", "Accor"],
  ["bestwestern.com", "Best Western"],
  ["wyndhamhotels.com", "Wyndham"],
  ["radissonhotels.com", "Radisson"],
  ["melia.com", "Meliá"],
  ["fourseasons.com", "Four Seasons"],
  ["ritzcarlton.com", "Ritz-Carlton"],
  ["waldorfastoria.com", "Waldorf Astoria"],
  ["sheratonhotels.com", "Sheraton"],
  ["westin.com", "Westin"],
  ["whotels.com", "W Hotels"],
  ["motel6.com", "Motel 6"],
  ["holidayinn.com", "Holiday Inn"],
  ["hamptoninn.com", "Hampton Inn"],
  ["doubletree.com", "DoubleTree"],
  ["vrbо.com", "VRBO"],
  ["hotels.com", "Hotels.com"],
  ["priceline.com", "Priceline"],
  ["kayak.com", "KAYAK"],
  ["skyscanner.com", "Skyscanner"],
  ["trivago.com", "trivago"],
  ["hotwire.com", "Hotwire"],
  ["lastminute.com", "lastminute.com"],
  ["booking.com", "Booking.com"],
  // ── Finance & Banking ──────────────────────────────────────────────────────
  ["jpmorgan.com", "JPMorgan Chase"],
  ["bankofamerica.com", "Bank of America"],
  ["wellsfargo.com", "Wells Fargo"],
  ["citibank.com", "Citibank"],
  ["barclays.com", "Barclays"],
  ["deutschebank.com", "Deutsche Bank"],
  ["bnpparibas.com", "BNP Paribas"],
  ["ubs.com", "UBS"],
  ["santander.com", "Santander"],
  ["bbva.com", "BBVA"],
  ["unicredit.com", "UniCredit"],
  ["lloyds.com", "Lloyds"],
  ["natwest.com", "NatWest"],
  ["ing.com", "ING"],
  ["rabobank.com", "Rabobank"],
  ["commerzbank.com", "Commerzbank"],
  ["standardchartered.com", "Standard Chartered"],
  ["td.com", "TD Bank"],
  ["rbc.com", "Royal Bank of Canada"],
  ["scotiabank.com", "Scotiabank"],
  ["bmo.com", "BMO"],
  ["cibc.com", "CIBC"],
  ["nab.com.au", "NAB"],
  ["commbank.com.au", "CommBank"],
  ["westpac.com.au", "Westpac"],
  ["anz.com", "ANZ"],
  ["cba.com.au", "CBA"],
  ["icbc.com.cn", "ICBC"],
  ["boc.cn", "Bank of China"],
  ["abchina.com", "Agricultural Bank of China"],
  ["ccb.com", "China Construction Bank"],
  ["fidelity.com", "Fidelity"],
  ["vanguard.com", "Vanguard"],
  ["blackrock.com", "BlackRock"],
  ["schwab.com", "Charles Schwab"],
  ["etrade.com", "E*TRADE"],
  ["tdameritrade.com", "TD Ameritrade"],
  ["nerdwallet.com", "NerdWallet"],
  ["mint.com", "Mint"],
  ["intuit.com", "Intuit"],
  ["quicken.com", "Quicken"],
  ["klarna.com", "Klarna"],
  ["afterpay.com", "Afterpay"],
  ["affirm.com", "Affirm"],
  ["chime.com", "Chime"],
  ["sofi.com", "SoFi"],
  ["revolut.com", "Revolut"],
  ["n26.com", "N26"],
  ["monzo.com", "Monzo"],
  ["starlingbank.com", "Starling Bank"],
  ["wise.com", "Wise"],
  ["transferwise.com", "TransferWise"],
  ["worldremit.com", "WorldRemit"],
  ["westernunion.com", "Western Union"],
  ["moneygram.com", "MoneyGram"],
  // ── Pharma & Healthcare ────────────────────────────────────────────────────
  ["pfizer.com", "Pfizer"],
  ["jnj.com", "Johnson & Johnson"],
  ["abbvie.com", "AbbVie"],
  ["merck.com", "Merck"],
  ["novartis.com", "Novartis"],
  ["roche.com", "Roche"],
  ["astrazeneca.com", "AstraZeneca"],
  ["bayer.com", "Bayer"],
  ["gsk.com", "GSK"],
  ["sanofi.com", "Sanofi"],
  ["lilly.com", "Eli Lilly"],
  ["amgen.com", "Amgen"],
  ["regeneron.com", "Regeneron"],
  ["modernatx.com", "Moderna"],
  ["biogen.com", "Biogen"],
  ["gilead.com", "Gilead Sciences"],
  ["bristol-myers.com", "Bristol Myers Squibb"],
  ["abbottlaboratories.com", "Abbott"],
  ["becton.com", "BD"],
  ["medtronic.com", "Medtronic"],
  ["stryker.com", "Stryker"],
  ["zimmer.com", "Zimmer Biomet"],
  ["edwards.com", "Edwards Lifesciences"],
  ["hologic.com", "Hologic"],
  ["danaher.com", "Danaher"],
  ["thermofisher.com", "Thermo Fisher"],
  ["illumina.com", "Illumina"],
  ["iqvia.com", "IQVIA"],
  ["labcorp.com", "LabCorp"],
  ["questdiagnostics.com", "Quest Diagnostics"],
  ["cigna.com", "Cigna"],
  ["humana.com", "Humana"],
  ["unitedhealth.com", "UnitedHealth"],
  ["aetna.com", "Aetna"],
  ["anthem.com", "Anthem"],
  ["cvs.com", "CVS Health"],
  ["walgreens.com", "Walgreens"],
  ["boots.com", "Boots"],
  ["celesio.com", "Celesio"],
  // ── Sports ─────────────────────────────────────────────────────────────────
  ["nfl.com", "NFL"],
  ["nhl.com", "NHL"],
  ["mlb.com", "MLB"],
  ["nba.com", "NBA"],
  ["mls.com", "MLS"],
  ["premierleague.com", "Premier League"],
  ["laliga.com", "La Liga"],
  ["bundesliga.com", "Bundesliga"],
  ["ligue1.com", "Ligue 1"],
  ["seriea.it", "Serie A"],
  ["formula1.com", "Formula 1"],
  ["motogp.com", "MotoGP"],
  ["nascar.com", "NASCAR"],
  ["wrc.com", "WRC"],
  ["rolex.com", "Rolex"],
  ["nbcsports.com", "NBC Sports"],
  ["bein.com", "beIN Sports"],
  ["eurosport.com", "Eurosport"],
  ["dazn.com", "DAZN"],
  ["olympic.org", "Olympics"],
  ["fifa.com", "FIFA"],
  ["ioc.ch", "IOC"],
  ["worldathletics.org", "World Athletics"],
  ["fiba.basketball", "FIBA"],
  ["ittf.com", "ITTF"],
  ["tennis.com", "Tennis"],
  ["wimbledon.com", "Wimbledon"],
  ["rolandgarros.com", "Roland Garros"],
  ["usopen.org", "US Open"],
  ["ausopen.com", "Australian Open"],
  ["ufc.com", "UFC"],
  ["wwe.com", "WWE"],
  ["boxingscene.com", "Boxing"],
  ["mlsoccer.com", "MLS Soccer"],
  ["decathlon.com", "Decathlon"],
  ["pro-direct.com", "Pro:Direct Sport"],
  ["sports.com", "Sports.com"],
  // ── Gaming ─────────────────────────────────────────────────────────────────
  ["activision.com", "Activision"],
  ["blizzard.com", "Blizzard"],
  ["riotgames.com", "Riot Games"],
  ["roblox.com", "Roblox"],
  ["minecraft.net", "Minecraft"],
  ["take2games.com", "Take-Two Interactive"],
  ["2k.com", "2K Games"],
  ["rockstargames.com", "Rockstar Games"],
  ["bethesda.net", "Bethesda"],
  ["squareenix.com", "Square Enix"],
  ["capcom.com", "Capcom"],
  ["konami.com", "Konami"],
  ["sega.com", "SEGA"],
  ["bandainamco.com", "Bandai Namco"],
  ["cdprojekt.com", "CD Projekt"],
  ["fromsoft.com", "FromSoftware"],
  ["codemasters.com", "Codemasters"],
  ["505games.com", "505 Games"],
  ["2kgames.com", "2K"],
  ["thq.com", "THQ Nordic"],
  ["deepsilver.com", "Deep Silver"],
  ["focus-home.com", "Focus Entertainment"],
  ["wargaming.net", "Wargaming"],
  ["naughtydog.com", "Naughty Dog"],
  ["ign.com", "IGN"],
  ["gamespot.com", "GameSpot"],
  ["kotaku.com", "Kotaku"],
  ["polygon.com", "Polygon"],
  ["pcgamer.com", "PC Gamer"],
  ["gamescom.de", "Gamescom"],
  // ── Media & Entertainment ──────────────────────────────────────────────────
  ["disney.com", "Disney"],
  ["hulu.com", "Hulu"],
  ["hbo.com", "HBO"],
  ["peacocktv.com", "Peacock"],
  ["paramountplus.com", "Paramount+"],
  ["appletv.apple.com", "Apple TV+"],
  ["discovery.com", "Discovery"],
  ["bbc.com", "BBC"],
  ["cnn.com", "CNN"],
  ["fox.com", "Fox"],
  ["nbcnews.com", "NBC News"],
  ["cbsnews.com", "CBS News"],
  ["abcnews.go.com", "ABC News"],
  ["nytimes.com", "The New York Times"],
  ["wsj.com", "The Wall Street Journal"],
  ["bloomberg.com", "Bloomberg"],
  ["reuters.com", "Reuters"],
  ["apnews.com", "AP News"],
  ["theguardian.com", "The Guardian"],
  ["telegraph.co.uk", "The Telegraph"],
  ["lemonde.fr", "Le Monde"],
  ["lefigaro.fr", "Le Figaro"],
  ["spiegel.de", "Der Spiegel"],
  ["bild.de", "Bild"],
  ["zeit.de", "Die Zeit"],
  ["corriere.it", "Corriere della Sera"],
  ["elpais.com", "El País"],
  ["marca.com", "Marca"],
  ["kicker.de", "kicker"],
  ["sky.com", "Sky"],
  ["canal-plus.com", "Canal+"],
  ["arte.tv", "ARTE"],
  ["rtl.com", "RTL"],
  ["prosieben.de", "ProSieben"],
  ["sat1.de", "SAT.1"],
  ["ard.de", "ARD"],
  ["zdf.de", "ZDF"],
  ["tf1.fr", "TF1"],
  ["france2.fr", "France 2"],
  ["m6.fr", "M6"],
  ["rai.it", "RAI"],
  ["mediaset.it", "Mediaset"],
  ["antenna3.es", "Antena 3"],
  ["sonymusic.com", "Sony Music"],
  ["universalmusic.com", "Universal Music"],
  ["atlanticrecords.com", "Atlantic Records"],
  ["interscope.com", "Interscope"],
  ["defjamarecordings.com", "Def Jam"],
  ["columbiarecords.com", "Columbia Records"],
  ["empiremusicgroup.com", "Empire"],
  ["beatsmusic.com", "Beats"],
  ["shazam.com", "Shazam"],
  ["soundcloud.com", "SoundCloud"],
  ["deezer.com", "Deezer"],
  ["tidal.com", "TIDAL"],
  ["pandora.com", "Pandora"],
  ["iheart.com", "iHeartRadio"],
  ["lastfm.com", "Last.fm"],
  ["bandcamp.com", "Bandcamp"],
  // ── Beauty & Cosmetics ─────────────────────────────────────────────────────
  ["loreal.com", "L'Oréal"],
  ["esteelauder.com", "Estée Lauder"],
  ["revlon.com", "Revlon"],
  ["maybelline.com", "Maybelline"],
  ["neutrogena.com", "Neutrogena"],
  ["olay.com", "Olay"],
  ["clinique.com", "Clinique"],
  ["maccosmetics.com", "MAC Cosmetics"],
  ["narsissist.com", "NARS"],
  ["urbandecay.com", "Urban Decay"],
  ["fentybeauty.com", "Fenty Beauty"],
  ["kyliejenner.com", "Kylie Cosmetics"],
  ["charlottetilbury.com", "Charlotte Tilbury"],
  ["toofaced.com", "Too Faced"],
  ["benefitcosmetics.com", "Benefit Cosmetics"],
  ["lancome.com", "Lancôme"],
  ["yslbeauty.com", "YSL Beauty"],
  ["armanibeauty.com", "Armani Beauty"],
  ["tomford.com", "Tom Ford"],
  ["natashadenona.com", "Natasha Denona"],
  ["patmcgrath.com", "Pat McGrath"],
  ["huda.com", "Huda Beauty"],
  ["morphebrushes.com", "Morphe"],
  ["milanicosmetics.com", "Milani"],
  ["nyxcosmetics.com", "NYX"],
  ["elf.com", "e.l.f. Cosmetics"],
  ["wet-n-wild.com", "Wet n Wild"],
  ["cerave.com", "CeraVe"],
  ["laneige.com", "LANEIGE"],
  ["tatcha.com", "Tatcha"],
  ["kiehlsince1851.com", "Kiehl's"],
  ["origins.com", "Origins"],
  ["dermalogica.com", "Dermalogica"],
  ["paulaschoice.com", "Paula's Choice"],
  ["theordinary.com", "The Ordinary"],
  ["drunk-elephant.com", "Drunk Elephant"],
  ["glow-recipe.com", "Glow Recipe"],
  ["olehenriksen.com", "Ole Henriksen"],
  ["fresh.com", "Fresh"],
  ["biossance.com", "Biossance"],
  ["pixi.com", "Pixi"],
  ["revolution.com", "Revolution"],
  ["catrice.eu", "Catrice"],
  ["essence-cosmetics.com", "Essence"],
  ["avon.com", "Avon"],
  ["oriflame.com", "Oriflame"],
  ["farmasi.com", "Farmasi"],
  ["dove.com", "Dove"],
  ["nivea.com", "NIVEA"],
  ["garnier.com", "Garnier"],
  ["pantene.com", "Pantene"],
  ["headandshoulders.com", "Head & Shoulders"],
  ["herbalessences.com", "Herbal Essences"],
  ["tresemme.com", "TRESemmé"],
  ["biosilk.com", "BioSilk"],
  ["moroccanoil.com", "Moroccanoil"],
  ["wella.com", "Wella"],
  ["schwarzkopf.com", "Schwarzkopf"],
  ["kerastase.com", "Kérastase"],
  // ── Telecom ────────────────────────────────────────────────────────────────
  ["verizon.com", "Verizon"],
  ["att.com", "AT&T"],
  ["t-mobile.com", "T-Mobile"],
  ["comcast.com", "Comcast"],
  ["charter.com", "Charter"],
  ["vodafone.com", "Vodafone"],
  ["orange.com", "Orange"],
  ["telefonica.com", "Telefónica"],
  ["telekom.de", "Deutsche Telekom"],
  ["bt.com", "BT"],
  ["sky.com", "Sky"],
  ["swisscom.ch", "Swisscom"],
  ["sunrise.ch", "Sunrise"],
  ["telstra.com.au", "Telstra"],
  ["docomo.com", "NTT Docomo"],
  ["softbank.jp", "SoftBank"],
  ["chinamobile.com", "China Mobile"],
  ["chinaunicom.com", "China Unicom"],
  ["sktelecom.com", "SK Telecom"],
  ["lguplus.com", "LG U+"],
  ["ktcorp.com", "KT Corporation"],
  ["bouygues.com", "Bouygues Telecom"],
  ["sfr.fr", "SFR"],
  ["free.fr", "Free"],
  ["iliad.fr", "iliad"],
  ["proton.me", "Proton"],
  ["fastmail.com", "Fastmail"],
  ["tutanota.com", "Tutanota"],
  // ── Insurance ──────────────────────────────────────────────────────────────
  ["allstate.com", "Allstate"],
  ["geico.com", "GEICO"],
  ["progressive.com", "Progressive"],
  ["libertymutual.com", "Liberty Mutual"],
  ["statefarm.com", "State Farm"],
  ["axa.com", "AXA"],
  ["allianz.com", "Allianz"],
  ["munichre.com", "Munich Re"],
  ["swissre.com", "Swiss Re"],
  ["zurichinsurance.com", "Zurich"],
  ["generali.com", "Generali"],
  ["manulife.com", "Manulife"],
  ["sunlife.com", "Sun Life"],
  ["prudential.com", "Prudential"],
  ["metlife.com", "MetLife"],
  ["nationwide.com", "Nationwide"],
  ["travelers.com", "Travelers"],
  ["chubb.com", "Chubb"],
  ["aiginsurance.com", "AIG"],
  ["hiscox.com", "Hiscox"],
  ["aviva.com", "Aviva"],
  ["lloydsoflondon.com", "Lloyd's of London"],
  // ── Home & Industrial ──────────────────────────────────────────────────────
  ["whirlpool.com", "Whirlpool"],
  ["miele.com", "Miele"],
  ["dyson.com", "Dyson"],
  ["irobot.com", "iRobot"],
  ["kitchenaid.com", "KitchenAid"],
  ["cuisinart.com", "Cuisinart"],
  ["breville.com", "Breville"],
  ["delonghi.com", "De'Longhi"],
  ["keurig.com", "Keurig"],
  ["instantpot.com", "Instant Pot"],
  ["ninja.com", "Ninja Kitchen"],
  ["philipshue.com", "Philips Hue"],
  ["nanoleaf.com", "Nanoleaf"],
  ["ring.com", "Ring"],
  ["nest.com", "Nest"],
  ["ecobee.com", "Ecobee"],
  ["tado.com", "Tado"],
  ["sonos.com", "Sonos"],
  ["bose.com", "Bose"],
  ["jbl.com", "JBL"],
  ["sennheiser.com", "Sennheiser"],
  ["akg.com", "AKG"],
  ["audio-technica.com", "Audio-Technica"],
  ["jabra.com", "Jabra"],
  ["plantronics.com", "Plantronics"],
  ["corsair.com", "Corsair"],
  ["razer.com", "Razer"],
  ["steelseries.com", "SteelSeries"],
  ["logitechg.com", "Logitech G"],
  ["hyperx.com", "HyperX"],
  ["astro.com", "ASTRO Gaming"],
  ["turtle beach.com", "Turtle Beach"],
  ["ikea.com", "IKEA"],
  ["wayfair.com", "Wayfair"],
  ["ashley.com", "Ashley Furniture"],
  ["westelm.com", "West Elm"],
  ["crate.com", "Crate & Barrel"],
  ["potterybarn.com", "Pottery Barn"],
  ["cb2.com", "CB2"],
  ["restoration hardware.com", "RH"],
  ["world market.com", "World Market"],
  ["homegoods.com", "HomeGoods"],
  ["tj maxx.com", "TJ Maxx"],
  ["marshalls.com", "Marshalls"],
  ["ross.com", "Ross"],
  // ── Education ─────────────────────────────────────────────────────────────
  ["coursera.org", "Coursera"],
  ["udemy.com", "Udemy"],
  ["edx.org", "edX"],
  ["khanacademy.org", "Khan Academy"],
  ["skillshare.com", "Skillshare"],
  ["masterclass.com", "MasterClass"],
  ["pluralsight.com", "Pluralsight"],
  ["codecademy.com", "Codecademy"],
  ["freecodecamp.org", "freeCodeCamp"],
  ["brilliant.org", "Brilliant"],
  ["udacity.com", "Udacity"],
  ["linkedin.com/learning", "LinkedIn Learning"],
  ["datacamp.com", "DataCamp"],
  ["treehouse.com", "Treehouse"],
  ["lynda.com", "Lynda"],
  ["sololearn.com", "SoloLearn"],
  ["rosettastone.com", "Rosetta Stone"],
  ["babbel.com", "Babbel"],
  ["memrise.com", "Memrise"],
  ["pimsleur.com", "Pimsleur"],
  ["chegg.com", "Chegg"],
  ["quizlet.com", "Quizlet"],
  ["studyblue.com", "StudyBlue"],
  ["anki.com", "Anki"],
  ["cambridgeenglish.org", "Cambridge English"],
  ["ielts.org", "IELTS"],
  ["toefl.org", "TOEFL"],
  ["pearson.com", "Pearson"],
  ["mcgrawhill.com", "McGraw-Hill"],
  ["cengage.com", "Cengage"],
  ["wiley.com", "Wiley"],
  ["springer.com", "Springer"],
  ["elsevier.com", "Elsevier"],
  ["nature.com", "Nature"],
  ["science.org", "Science"],
  ["jstor.org", "JSTOR"],
  // ── Automotive Parts & Services ────────────────────────────────────────────
  ["autozone.com", "AutoZone"],
  ["orielly.com", "O'Reilly Auto Parts"],
  ["advanceautoparts.com", "Advance Auto Parts"],
  ["napaonline.com", "NAPA Auto Parts"],
  ["pep boys.com", "Pep Boys"],
  ["firestone.com", "Firestone"],
  ["goodyear.com", "Goodyear"],
  ["michelin.com", "Michelin"],
  ["bridgestone.com", "Bridgestone"],
  ["continental.com", "Continental"],
  ["pirelli.com", "Pirelli"],
  ["hankooktire.com", "Hankook"],
  ["yokohamatire.com", "Yokohama"],
  ["toyo.com", "Toyo Tires"],
  ["kumho.com", "Kumho"],
  ["bf goodrich.com", "BFGoodrich"],
  ["dunloptires.com", "Dunlop"],
  ["bosch.com", "Bosch"],
  ["delphi.com", "Delphi"],
  ["denso.com", "DENSO"],
  ["mann-filter.com", "MANN-FILTER"],
  ["sachs.de", "Sachs"],
  ["valeo.com", "Valeo"],
  ["brembo.com", "Brembo"],
  ["akebono.com", "Akebono"],
  // ── Logistics & Shipping ───────────────────────────────────────────────────
  ["usps.com", "USPS"],
  ["royalmail.com", "Royal Mail"],
  ["laposte.fr", "La Poste"],
  ["deutschepost.de", "Deutsche Post"],
  ["postnl.nl", "PostNL"],
  ["posteitaliane.it", "Poste Italiane"],
  ["correos.es", "Correos"],
  ["japanpost.jp", "Japan Post"],
  ["auspost.com.au", "Australia Post"],
  ["canpost.ca", "Canada Post"],
  ["dhl.com", "DHL"],
  ["fedex.com", "FedEx"],
  ["ups.com", "UPS"],
  ["tnt.com", "TNT"],
  ["gls-group.eu", "GLS"],
  ["dpd.com", "DPD"],
  ["chronopost.fr", "Chronopost"],
  ["colissimo.fr", "Colissimo"],
  ["hermes-europe.co.uk", "Hermes"],
  ["yodel.co.uk", "Yodel"],
  ["evri.com", "Evri"],
  ["maersk.com", "Maersk"],
  ["msc.com", "MSC"],
  ["cosco.com", "COSCO"],
  ["evergreen-marine.com", "Evergreen"],
  ["hapag-lloyd.com", "Hapag-Lloyd"],
  ["cma-cgm.com", "CMA CGM"],
  ["yangming.com", "Yang Ming"],
  ["hmm21.com", "HMM"],
  // ── Energy & Mining ────────────────────────────────────────────────────────
  ["exxonmobil.com", "ExxonMobil"],
  ["chevron.com", "Chevron"],
  ["bp.com", "BP"],
  ["total.com", "TotalEnergies"],
  ["eni.com", "ENI"],
  ["equinor.com", "Equinor"],
  ["petrobras.com.br", "Petrobras"],
  ["gazprom.com", "Gazprom"],
  ["lukoil.com", "Lukoil"],
  ["bhp.com", "BHP"],
  ["riotinto.com", "Rio Tinto"],
  ["glencore.com", "Glencore"],
  ["angloamerican.com", "Anglo American"],
  ["barrick.com", "Barrick Gold"],
  ["newmontmining.com", "Newmont"],
  ["vale.com", "Vale"],
  ["arcelor.com", "ArcelorMittal"],
  ["thyssenkrupp.com", "Thyssenkrupp"],
  ["salzgitter.de", "Salzgitter"],
  ["ssab.com", "SSAB"],
  ["nippon-steel.com", "Nippon Steel"],
  ["posco.com", "POSCO"],
  ["baosteel.com", "Baosteel"],
  ["nextera.com", "NextEra Energy"],
  ["duke-energy.com", "Duke Energy"],
  ["dominion.com", "Dominion Energy"],
  ["enel.com", "Enel"],
  ["rwe.com", "RWE"],
  ["e.on.com", "E.ON"],
  ["engie.com", "Engie"],
  ["iberdrola.com", "Iberdrola"],
  ["acciona.com", "Acciona"],
  ["orsted.com", "Ørsted"],
  ["vestas.com", "Vestas"],
  ["siemens-energy.com", "Siemens Energy"],
  // ── Luxury ────────────────────────────────────────────────────────────────
  ["lvmh.com", "LVMH"],
  ["kering.com", "Kering"],
  ["richemont.com", "Richemont"],
  ["swatch.com", "Swatch"],
  ["longines.com", "Longines"],
  ["breitling.com", "Breitling"],
  ["iwc.com", "IWC Schaffhausen"],
  ["panerai.com", "Panerai"],
  ["jaeger-lecoultre.com", "Jaeger-LeCoultre"],
  ["patek.com", "Patek Philippe"],
  ["vacheron.com", "Vacheron Constantin"],
  ["piguet.com", "Audemars Piguet"],
  ["chopard.com", "Chopard"],
  ["harry-winston.com", "Harry Winston"],
  ["tiffany.com", "Tiffany & Co."],
  ["vanbigel.com", "Van Cleef & Arpels"],
  ["piaget.com", "Piaget"],
  ["graff.com", "Graff"],
  ["bulgari.com", "Bvlgari"],
  ["cartier.com", "Cartier"],
  ["hermes.com", "Hermès"],
  ["chloe.com", "Chloé"],
  ["stella mccartney.com", "Stella McCartney"],
  ["alexandermcqueen.com", "Alexander McQueen"],
  ["viviennewestwood.com", "Vivienne Westwood"],
  ["paulsmith.co.uk", "Paul Smith"],
  ["dunhill.com", "Dunhill"],
  ["montblanc.com", "Montblanc"],
  ["s.t-dupont.com", "S.T. Dupont"],
  // ── Real Estate & Construction ─────────────────────────────────────────────
  ["zillow.com", "Zillow"],
  ["realtor.com", "Realtor.com"],
  ["redfin.com", "Redfin"],
  ["trulia.com", "Trulia"],
  ["century21.com", "Century 21"],
  ["remax.com", "RE/MAX"],
  ["kw.com", "Keller Williams"],
  ["coldwellbanker.com", "Coldwell Banker"],
  ["jll.com", "JLL"],
  ["cbre.com", "CBRE"],
  ["colliers.com", "Colliers"],
  ["costargroup.com", "CoStar"],
  ["rightmove.co.uk", "Rightmove"],
  ["zoopla.co.uk", "Zoopla"],
  ["idealista.com", "Idealista"],
  ["seloger.com", "SeLoger"],
  ["leboncoin.fr", "leboncoin"],
  ["immo scout24.de", "ImmoScout24"],
  ["vk.com", "VK"],
  // ── Miscellaneous / Internet Services ─────────────────────────────────────
  ["google.com", "Google"],
  ["microsoft.com", "Microsoft"],
  ["amazon.com", "Amazon"],
  ["apple.com", "Apple"],
  ["meta.com", "Meta"],
  ["ibm.com", "IBM"],
  ["sap.com", "SAP"],
  ["qualcomm.com", "Qualcomm"],
  ["texas-instruments.com", "Texas Instruments"],
  ["micron.com", "Micron Technology"],
  ["asml.com", "ASML"],
  ["tsmc.com", "TSMC"],
  ["broadcom.com", "Broadcom"],
  ["marvell.com", "Marvell"],
  ["mediatek.com", "MediaTek"],
  ["arm.com", "Arm"],
  ["palantir.com", "Palantir"],
  ["snowflake.com", "Snowflake"],
  ["databricks.com", "Databricks"],
  ["cloudera.com", "Cloudera"],
  ["tableau.com", "Tableau"],
  ["looker.com", "Looker"],
  ["domo.com", "Domo"],
  ["qlik.com", "Qlik"],
  ["microstrategy.com", "MicroStrategy"],
  ["sas.com", "SAS"],
  ["workday.com", "Workday"],
  ["servicenow.com", "ServiceNow"],
  ["solarwinds.com", "SolarWinds"],
  ["crowdstrike.com", "CrowdStrike"],
  ["paloaltonetworks.com", "Palo Alto Networks"],
  ["fortinet.com", "Fortinet"],
  ["checkpoint.com", "Check Point"],
  ["symantec.com", "Symantec"],
  ["kaspersky.com", "Kaspersky"],
  ["eset.com", "ESET"],
  ["avast.com", "Avast"],
  ["avg.com", "AVG"],
  ["bitdefender.com", "Bitdefender"],
  ["malwarebytes.com", "Malwarebytes"],
  ["nordvpn.com", "NordVPN"],
  ["expressvpn.com", "ExpressVPN"],
  ["surfshark.com", "Surfshark"],
  ["cyberghost.com", "CyberGhost"],
  ["1password.com", "1Password"],
  ["lastpass.com", "LastPass"],
  ["bitwarden.com", "Bitwarden"],
  ["dashlane.com", "Dashlane"],
  ["clickup.com", "ClickUp"],
  ["notion.so", "Notion"],
  ["airtable.com", "Airtable"],
  ["smartsheet.com", "Smartsheet"],
  ["wrike.com", "Wrike"],
  ["basecamp.com", "Basecamp"],
  ["jira.com", "Jira"],
  ["confluence.com", "Confluence"],
  ["miro.com", "Miro"],
  ["lucidchart.com", "Lucidchart"],
  ["draw.io", "draw.io"],
  ["invision.com", "InVision"],
  ["zeplin.io", "Zeplin"],
  ["abstract.com", "Abstract"],
  ["principle.app", "Principle"],
  ["marvel.app", "Marvel"],
  ["proto.io", "Proto.io"],
  ["hotjar.com", "Hotjar"],
  ["mixpanel.com", "Mixpanel"],
  ["amplitude.com", "Amplitude"],
  ["segment.com", "Segment"],
  ["braze.com", "Braze"],
  ["klaviyo.com", "Klaviyo"],
  ["activecampaign.com", "ActiveCampaign"],
  ["constant contact.com", "Constant Contact"],
  ["sendinblue.com", "Brevo"],
  ["benchmark.email", "Benchmark Email"],
  ["campaign monitor.com", "Campaign Monitor"],
  ["getresponse.com", "GetResponse"],
  ["aweber.com", "AWeber"],
  ["convertkit.com", "ConvertKit"],
  ["drip.com", "Drip"],
  ["infusionsoft.com", "Keap"],
  ["pardot.com", "Pardot"],
  ["marketo.com", "Marketo"],
  ["eloqua.com", "Eloqua"],
  ["hootsuite.com", "Hootsuite"],
  ["buffer.com", "Buffer"],
  ["sprout social.com", "Sprout Social"],
  ["later.com", "Later"],
  ["canva.com", "Canva"],
  ["crello.com", "Crello"],
  ["piktochart.com", "Piktochart"],
  ["infogram.com", "Infogram"],
  ["visme.co", "Visme"],
  ["loom.com", "Loom"],
  ["vidyard.com", "Vidyard"],
  ["wistia.com", "Wistia"],
  ["vimeo.com", "Vimeo"],
  ["youtube.com", "YouTube"],
  ["dailymotion.com", "Dailymotion"],
  ["rumble.com", "Rumble"],
  ["odysee.com", "Odysee"],
  ["peertube.social", "PeerTube"],
  ["twitch.tv", "Twitch"],
  ["mixer.com", "Mixer"],
  ["dlive.tv", "DLive"],
  ["kick.com", "Kick"],
  ["trovo.live", "Trovo"],
  ["nimo.tv", "Nimo TV"],
  ["caffeine.tv", "Caffeine"],
  ["streamyard.com", "StreamYard"],
  ["restream.io", "Restream"],
  ["obs.com", "OBS Studio"],
  ["nvidia.com", "NVIDIA"],
  ["amd.com", "AMD"],
  ["intel.com", "Intel"],
];
